views/index.py
from flask import Blueprint, render_template
from models import Player, Tournament

bp = Blueprint('index', __name__, url_prefix='/')


@bp.route('/', methods=['GET'])
def index():
    players = Player.execute_select()[:10]
    tournaments = Tournament.execute_select()[:10]
    return render_template('index.html', players=players, tournaments=tournaments)

views/players.py
from flask import Blueprint, render_template, request, redirect
from models import PlayerModel, City, Rank, NationalRank
from utils import render_table, render_select, render_input, render_label, render_row, render_link

bp = Blueprint('players', __name__, url_prefix='/players')


@bp.route('/', methods=['GET'])
def players():
    player_list = PlayerModel.info()
    player_ids = []
    table_data = []
    for idx, row in enumerate(player_list, start=1):
        player_ids.append(row[0])
        table_data.append([idx, render_link(f"/players/{row[0]}", row[1])] + list(row)[2:])

    column_names = ['№ з/п', 'Прізвище та ім\'я', 'Місто', 'Рейтинг', 'Ранг', 'Розряд', 'PIN']
    table = render_table(column_names, table_data)
    return render_template('players.html', table=table)


@bp.route('/<string:player_id>', methods=['GET'])
def player_info(player_id):
    player_data = PlayerModel.info(player_id)[0][1:]
    data = zip(['Прізвище та ім\'я', 'Місто', 'Рейтинг', 'Ранг', 'Розряд', 'PIN'], player_data)
    column_names = ['Поле', 'Значення']
    table = render_table(column_names, data)
    return render_template('player.html', player_data=player_data, table=table, player_id=player_id)


@bp.route('/add', methods=['GET', 'POST'])
def add_player():
    if request.method == 'POST':
        return redirect('/players')

    form = '\n'.join([
        '<div class="container">',
        f'<form action="/players/add" method="post">',
        render_row(render_label('last_name', 'Прізвище', {'class': 'col-25'}),
                   render_input('text', {'name': 'last_name'}, {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('first_name', "Ім'я", {'class': 'col-25'}),
                   render_input('text', {'name': 'first_name'}, {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('city_id', "Місто", {'class': 'col-25'}),
                   render_select('city_id', City.info(), div_attrs={'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('rating', "Рейтинг", {'class': 'col-25'}),
                   render_input('number', {'name': 'rating', 'min': '100', 'max': '3000', 'step': '0.001'},
                                {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('rank_id', "Ранг", {'class': 'col-25'}),
                   render_select('rank_id', Rank.info(), div_attrs={'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('national_rank_id', "Розряд", {'class': 'col-25'}),
                   render_select('national_rank_id', NationalRank.info(), div_attrs={'class': 'col-75'}),
                   {'class': 'row'}),
        render_row('', render_input('submit', {'value': 'Submit'}), {'class': 'row'}),
        '</form>',
        '</div>',
    ])

    return render_template('add_player.html', form=form)


@bp.route('/<string:player_id>/edit', methods=['GET', 'POST'])
def edit_player(player_id):
    if request.method == 'POST':
        request_form = request.form
        PlayerModel.update(player_id, **request_form)
        return redirect(f'/players/{player_id}')

    player_data = PlayerModel.info(player_id, False, True)[0]
    print(player_data)
    form = '\n'.join([
        '<div class="container">',
        f'<form action="/players/{player_id}/edit" method="post">',
        render_row(render_label('last_name', 'Прізвище', {'class': 'col-25'}),
                   render_input('text', {'name': 'last_name', 'value': player_data[1]}, {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('first_name', "Ім'я", {'class': 'col-25'}),
                   render_input('text', {'name': 'first_name', 'value': player_data[2]}, {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('city_id', "Місто", {'class': 'col-25'}),
                   render_select('city_id', City.info(), player_data[3], {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('rating', "Рейтинг", {'class': 'col-25'}),
                   render_input('number', {'name': 'rating',
                                           'value': player_data[4],
                                           'min': '100',
                                           'max': '3000',
                                           'step': '0.001'},
                                {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('rank_id', "Ранг", {'class': 'col-25'}),
                   render_select('rank_id', Rank.info(), player_data[5], {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row(render_label('national_rank_id', "Розряд", {'class': 'col-25'}),
                   render_select('national_rank_id', NationalRank.info(), player_data[6], {'class': 'col-75'}),
                   {'class': 'row'}),
        render_row('', render_input('submit', {'value': 'Submit'}), {'class': 'row'}),
        '</form>',
        '</div>',
    ])

    return render_template('edit_player.html', player_data=player_data, form=form, player_id=player_id)

views/players_view.py
import mysql.connector
from flask import Blueprint, render_template, request, redirect
from flask.helpers import url_for, flash

from models import City, Rank, NationalRank, Player, Participant

from utils import (
    render_text_input_row,
    render_number_input_row,
    render_checkbox_row,
    render_select_row,
    render_submit
)

bp = Blueprint('players', __name__, url_prefix='/players')


@bp.route('/', methods=['GET'])
def players():
    all_players = Player.execute_select()
    return render_template('player_list.html', players=all_players)


@bp.route('/<int:player_id>', methods=['GET'])
def player_info(player_id):
    player = Player.execute_select({'id': player_id})[0]
    participant = Participant.execute_select({'player_id': player.id}, [('t.date_start', False)])
    return render_template('player_info.html', player=player, participant=participant)


@bp.route('/add', methods=['GET', 'POST'])
def add_player():
    error = None
    if request.method == 'POST':
        insert_data = dict(request.form)
        insert_data['is_active'] = 'is_active' in insert_data.keys()
        try:
            player_id = Player.execute_insert([insert_data])[0]
            flash('Гравець створений', 'isa_success')
            return redirect(url_for('.player_info', player_id=player_id))
        except mysql.connector.Error as err:
            flash(err.msg)

    cities = City.select_attrs(['id', 'name'])
    ranks = Rank.select_attrs(['id', 'name'])
    national_ranks = NationalRank.select_attrs(['id', 'name'])

    form = '\n'.join([
        '<div class="container">',
        f'<form action="/players/add" method="post">',
        render_text_input_row("last_name", "Прізвище"),
        render_text_input_row("first_name", "Ім'я"),
        render_select_row('city_id', "Місто", cities),
        render_number_input_row('rating', "Рейтинг", '100', '3000', '0.001'),
        render_select_row('rank_id', "Ранг", ranks),
        render_select_row('national_rank_id', "Розряд", national_ranks),
        render_text_input_row("pin", "EGF PIN"),
        render_checkbox_row('is_active', "Активний"),
        render_submit(),
        '</form>',
        '</div>',
    ])

    return render_template('add_player.html', form=form, error=error)


@bp.route('/<string:player_id>/edit', methods=['GET', 'POST'])
def edit_player(player_id):
    if request.method == 'POST':
        update_data = dict(request.form)
        update_data['is_active'] = 'is_active' in update_data.keys()
        try:
            Player.execute_update(player_id, **update_data)
            flash('Дані гравця оновлені', 'isa_success')
            return redirect(url_for('.players'))
        except mysql.connector.Error as err:
            flash(err.msg, 'isa_error')

        return redirect(url_for('.player_info', player_id=player_id))

    player = Player.execute_select({'id': player_id})[0]

    cities = City.select_attrs(['id', 'name'])
    ranks = Rank.select_attrs(['id', 'name'])
    national_ranks = NationalRank.select_attrs(['id', 'name'])

    form = '\n'.join([
        '<div class="container">',
        f'<form action="/players/{player_id}/edit" method="post">',
        render_text_input_row("last_name", "Прізвище", player.last_name),
        render_text_input_row("first_name", "Ім'я", player.first_name),
        render_select_row('city_id', "Місто", cities, player.city.id),
        render_number_input_row('rating', "Рейтинг", '100', '3000', '0.001', player.rating),
        render_select_row('rank_id', "Ранг", ranks, player.rank.id),
        render_select_row('national_rank_id', "Розряд", national_ranks, player.national_rank.id),
        render_text_input_row("pin", "EGF PIN", player.pin),
        render_checkbox_row('is_active', "Активний", player.is_active),
        render_submit(),
        '</form>',
        '</div>',
    ])

    return render_template('edit_player.html', player=player, form=form)


@bp.route('/<string:player_id>/delete', methods=['GET', 'POST'])
def delete_player(player_id):
    try:
        Player.execute_delete([player_id])
        flash('Гравець видалений', 'isa_success')
        return redirect(url_for('.players'))
    except mysql.connector.Error as err:
        flash(err.msg, 'isa_error')
        return redirect(url_for('.player_info', player_id=player_id))

views/tournaments_view.py
import datetime

import mysql.connector
from flask import Blueprint, render_template, url_for, request, redirect, flash
from collections import defaultdict
from models import City, Tournament, Participant, Pairing
from parser import TournamentParser
from utils import (
    render_table,
    render_link,
    render_text_input_row,
    render_select_row,
    render_checkbox_row,
    render_date_row,
    render_file_row,
    render_submit
)

bp = Blueprint('tournaments', __name__, url_prefix='/tournaments')
ALLOWED_EXTENSIONS = {'txt', 'csv'}
TOURNAMENT_LIST_ATTRS = ['name', 'city.name', 'date_start', 'date_end', 'pin', 'is_ranked']


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@bp.route('/', methods=['GET'])
def tournaments():
    tournament_list = Tournament.execute_select()
    table_data = []
    for idx, tournament in enumerate(tournament_list, start=1):
        tr_data = [render_link(url_for('.tournament_info', tournament_id=tournament.id), idx),
                   render_link(url_for('.tournament_info', tournament_id=tournament.id), tournament.name)]
        tr_data.extend(tournament.get_attrs('city.name', 'date_start', 'date_end', 'pin', 'is_ranked'))
        table_data.append(tr_data)

    column_names = ['№ з/п', 'Назва', 'Місто', 'Дата початку', 'Дата завершення', 'PIN', 'Рейтинговий']
    table = render_table(column_names, table_data)
    return render_template('tournament_list.html', table=table)


@bp.route('/<string:tournament_id>', methods=['GET'])
def tournament_info(tournament_id):
    tournament = Tournament.execute_select({'id': tournament_id})[0]
    pairings = Pairing.execute_select({'tp.tournament_id': tournament_id})

    aggregated_pairings = defaultdict(list)

    for pairing in pairings:
        aggregated_pairings[pairing.player].append(pairing.get_result())

    rounds = max([len(games) for games in aggregated_pairings.values()])

    return render_template('tournament_info.html',
                           tournament=tournament,
                           pairings=aggregated_pairings,
                           rounds=rounds)


@bp.route('/<string:tournament_id>/edit', methods=['GET', 'POST'])
def edit_tournament(tournament_id):
    edit_url = url_for('.edit_tournament', tournament_id=tournament_id)

    if request.method == 'POST':
        update_data = dict(request.form)
        update_data['is_ranked'] = 'is_ranked' in update_data.keys()
        update_data['date_start'] = request.form.getlist('date_start')[0]
        update_data['date_end'] = request.form.getlist('date_end')[0]
        try:
            Tournament.execute_update(tournament_id, update_data)
            flash('Дані турніру оновлені', 'isa_success')
            return redirect(url_for('.tournament_info', tournament_id=tournament_id))

        except mysql.connector.Error as err:
            flash(err.msg, 'isa_error')
            return redirect(edit_url)

    tournament = Tournament.execute_select({'id': tournament_id})[0]
    cities = City.select_attrs(['id', 'name'])

    form = '\n'.join([
        '<div class="container">',
        f'<form action="{edit_url}" method="post">',
        render_text_input_row("name", "Назва", tournament.name),
        render_select_row('city_id', "Місто", cities, tournament.city.id),
        render_date_row('date_start', 'Дата початку', tournament.date_start),
        render_date_row('date_end', 'Дата закінчення', tournament.date_end),
        render_text_input_row("pin", "EGF PIN", tournament.pin),
        render_checkbox_row('is_ranked', "Рейтинговий", tournament.is_ranked),
        render_submit(),
        '</form>',
        '</div>',
    ])

    return render_template('edit_tournament.html', tournament=tournament, form=form)


@bp.route('/add', methods=['GET', 'POST'])
def add_tournament():
    add_url = url_for('.add_tournament')

    if request.method == 'POST':
        file = request.files['file']

        filename = file.filename
        if not filename:
            flash('Додайте файл з турнірними даними', 'isa_warning')
            return redirect(url_for('.add_tournament'))

        if not allowed_file(filename):
            flash('Файл має бути текстовим', 'isa_error')
            return redirect(url_for('.add_tournament'))

        insert_data = dict(request.form)
        insert_data['is_ranked'] = 'is_ranked' in insert_data.keys()
        insert_data['date_start'] = request.form.getlist('date_start')[0]
        insert_data['date_end'] = request.form.getlist('date_end')[0]
        tournament_id = None
        try:
            tournament_id = Tournament.execute_insert([insert_data])[0]
            parser = TournamentParser(file.read(), tournament_id)
            parser.run()
        except Exception:
            flash('Oops!', 'isa_error')
            if tournament_id:
                pairing_ids = Pairing.select_attrs(['id'], {'tp.tournament_id': tournament_id})
                existing_participant_ids = Participant.select_attrs(['id'], {'tournament_id': tournament_id})
                Pairing.execute_delete([p[0] for p in pairing_ids])
                Participant.execute_delete([p[0] for p in existing_participant_ids])
                Tournament.execute_delete([tournament_id])
            return redirect(url_for('.add_tournament'))
        return redirect(url_for('.tournament_info', tournament_id=tournament_id))

    cities = City.select_attrs(['id', 'name'])

    form = '\n'.join([
        '<div class="container">',
        f'<form action="{add_url}" enctype="multipart/form-data" method="post">',
        render_text_input_row("name", "Назва"),
        render_select_row('city_id', "Місто", cities),
        render_date_row('date_start', 'Дата початку', str(datetime.date.today())),
        render_date_row('date_end', 'Дата закінчення', str(datetime.date.today())),
        render_text_input_row("pin", "EGF PIN"),
        render_checkbox_row('is_ranked', "Рейтинговий"),
        render_file_row('file', 'Файл'),
        render_submit(),
        '</form>',
        '</div>',
    ])

    return render_template('add_tournament.html', form=form)


@bp.route('/<string:tournament_id>/delete', methods=['GET', 'POST'])
def delete_tournament(tournament_id):
    try:
        pairing_ids = Pairing.select_attrs(['id'], {'tp.tournament_id': tournament_id})
        existing_participant_ids = Participant.select_attrs(['id'], {'tournament_id': tournament_id})
        Pairing.execute_delete([str(p[0]) for p in pairing_ids])
        Participant.execute_delete([str(p[0]) for p in existing_participant_ids])
        Tournament.execute_delete([str(tournament_id)])
        flash('Турнір видалений', 'isa_success')
        return redirect(url_for('.tournaments'))
    except mysql.connector.Error as err:
        flash(err.msg, 'isa_error')
        return redirect(url_for('.tournament_info', tournament_id=tournament_id))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Index</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='tables.css') }}" />
</head>
<body>
<div class="header">
    <a href="{{ url_for('index.index') }}" class="logo">База турнірів по го</a>
    <div class="header-right">
        <a href="{{ url_for('players.players') }}">Гравці</a>
        <a href="{{ url_for('tournaments.tournaments') }}">Турніри</a>
    </div>
</div>
<div class="table-container">
    <div style="display:inline-block; width:50%;">
        <table class="ugd_table">
            <tr><th>ТОП-10 гравців</th></tr>
            {% for p in players %}
            <tr><td><a href="{{ url_for('players.player_info', player_id=p.id) }}">{{ p.full_name }}</a></td></tr>
            {% endfor %}
        </table>
    </div>
    <div style="display:inline-block; width:50%;">
        <table class="ugd_table">
            <tr><th>Останні турніри</th></tr>
            {% for t in tournaments %}
            <tr><td><a href="{{ url_for('tournaments.tournament_info', tournament_id=t.id) }}">{{ t.name }}</a></td></tr>
            {% endfor %}
        </table>
    </div>
</div>
</body>
</html>

templates/player_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ player.full_name }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='tables.css') }}"/>
</head>
<body>
<div class="header">
    <a href="{{ url_for('players.player_info', player_id=player.id) }}" class="logo">{{ player.full_name }} ({{
        player.rank.name }})</a>
    <a href="{{ url_for('players.edit_player', player_id=player.id) }}">Редагувати</a>
    <a href="{{ url_for('players.delete_player', player_id=player.id) }}" onclick="return confirm('Ви впевнені?');">Видалити</a>
    <div class="header-right">
        <a href="{{ url_for('players.players') }}" class="active">Гравці</a>
        <a href="{{ url_for('tournaments.tournaments') }}">Турніри</a>
    </div>
</div>
<div class="table-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <p class="{{ category }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <table class="ugd_table" style="width: 50%">
        <tr>
            <td class="col-25" style="text-align: right">Повне ім'я:</td>
            <td class="col-75" style="text-align: left"><b>{{ player.full_name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Місто:</td>
            <td class="col-75" style="text-align: left"><b>{{ player.city.name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Ранг:</td>
            <td class="col-75" style="text-align: left"><b>{{ player.rank.name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Розряд або звання:</td>
            <td class="col-75" style="text-align: left"><b>{{ player.national_rank.name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Рейтинг:</td>
            <td class="col-75" style="text-align: left"><b>{{ (player.rating|string).rstrip('0').rstrip('.') }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Турнірів зіграно:</td>
            <td class="col-75" style="text-align: left"><b>{{ participant|length }}</b></td>
        </tr>
    </table>
    {%  if participant %}
    <table class="ugd_table">
        <tr>
            <th>Дата</th>
            <th>Місто</th>
            <th>Назва</th>
            <th>Місце</th>
            <th>Рейтинг</th>
        </tr>
        {% for p in participant %}
        <tr>
            <td>{{ p.tournament.date_start }}</td>
            <td>{{ p.tournament.city.name or '' }}</td>
            <td><a href="{{ url_for('tournaments.tournament_info', tournament_id=p.tournament.id) }}">{{ p.tournament.name }}</a></td>
            <td>{{ p.place }}</td>
            {% if p.rating_end and p.rating_end %}
                {% if p.rating_start < p.rating_end %}
                <td style="color: green">{{ (p.rating_start|string).rstrip('0').rstrip('.') }} →
                                         {{ (p.rating_end|string).rstrip('0').rstrip('.') }}</td>
                {% elif p.rating_start > p.rating_end %}
                <td style="color: red">{{ (p.rating_start|string).rstrip('0').rstrip('.') }} →
                                         {{ (p.rating_end|string).rstrip('0').rstrip('.') }}</td>
                {% else %}
                <td style="color: black">{{ (p.rating_start|string).rstrip('0').rstrip('.') }} →
                                         {{ (p.rating_end|string).rstrip('0').rstrip('.') }}</td>
                {% endif %}
            {% elif p.rating_start %}
            <td style="color: black">{{ (p.rating_start|string).rstrip('0').rstrip('.') }}</td>
            {% elif p.rating_end %}
            <td style="color: black">{{ (p.rating_end|string).rstrip('0').rstrip('.') }}</td>
            {% else %}
            <td style="color: black"></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
</body>
</html>

templates/player_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Гравці</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='tables.css') }}"/>
</head>
<body>
<div class="header">
    <a href="{{ url_for('index.index') }}" class="logo">База турнірів по го</a>
    <a href="{{ url_for('players.add_player') }}">Додати гравця</a>
    <div class="header-right">
        <a href="{{ url_for('players.players') }}" class="active">Гравці</a>
        <a href="{{ url_for('tournaments.tournaments') }}">Турніри</a>
    </div>
</div>
<div class="table-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <p class="{{ category }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% if players %}
    <table class="ugd_table">
        <tr>
            <th>№ з/п</th>
            <th>Прізвище та ім'я</th>
            <th>Місто</th>
            <th>Рейтинг</th>
            <th>Ранг</th>
            <th>Розряд</th>
            <th>PIN</th>
            <th>Активний</th>
        </tr>
        {% for p in players %}
        <tr>
            <td><a href="{{ url_for('players.player_info', player_id=p.id) }}">{{ loop.index }}</a></td>
            <td><a href="{{ url_for('players.player_info', player_id=p.id) }}">{{ p.full_name }}</a></td>
            <td>{{ p.city.name or '' }}</td>
            <td>{{ (p.rating|string).rstrip('0').rstrip('.') or '' }}</td>
            <td>{{ p.rank.name or '' }}</td>
            <td>{{ p.national_rank.abbreviate or '' }}</td>
            <td>{{ p.pin or '' }}</td>
            <td>{{ '+' if p.is_active else '' }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
</body>
</html>

templates/tournament_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Турніри</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='tables.css') }}"/>
</head>
<body>
<div class="header">
    <a href="{{ url_for('tournaments.tournament_info', tournament_id=tournament.id) }}" class="logo">
        {{ tournament.name }}</a>
    <a href="{{ url_for('tournaments.edit_tournament', tournament_id=tournament.id) }}">Редагувати</a>
    <a href="{{ url_for('tournaments.delete_tournament', tournament_id=tournament.id) }}" onclick="return confirm('Ви впевнені?');">Видалити</a>
    <div class="header-right">
        <a href="{{ url_for('players.players') }}">Гравці</a>
        <a href="{{ url_for('tournaments.tournaments') }}" class="active">Турніри</a>
    </div>
</div>

<div class="table-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <p class="{{ category }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <table class="ugd_table" style="width: 50%">
        <tr>
            <td class="col-25" style="text-align: right">Назва:</td>
            <td class="col-75" style="text-align: left"><b>{{ tournament.name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Місце:</td>
            <td class="col-75" style="text-align: left"><b>{{ tournament.city.name }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Дата початку:</td>
            <td class="col-75" style="text-align: left"><b>{{ tournament.date_start }}</b></td>
        </tr>
        <tr>
            <td class="col-25" style="text-align: right">Дата закінчення:</td>
            <td class="col-75" style="text-align: left"><b>{{ tournament.date_end }}</b></td>
        </tr>
    </table>
    <table class="ugd_table">
        <tr>
            <th>№ з/п</th>
            <th>Прізвище та ім'я</th>
            <th>Місто</th>
            <th>Ранг</th>
            <th>Рейтинг</th>
            {% for i in range(rounds) %}
            <th>{{ i + 1 }}</th>
            {% endfor %}
        </tr>
        {% for player, rounds in pairings.items() %}
        <tr>
            <td style="color: black">{{ player.place }}</td>
            <td style="color: black"><a href="{{ url_for('players.player_info', player_id=player.player.id) }}">{{ player.player.full_name }}</a></td>
            <td style="color: black">{{ player.player.city.name or '' }}</td>
            <td style="color: black">{{ player.rank.name or '' }}</td>
            <td style="color: black">{{ (player.rating_start|string).rstrip('0').rstrip('.') if player.rating_start else '' }}</td>
            {% for item in rounds %}
            {% if '+' in item|string %}
            <td style="color: green">{{ item }}</td>
            {% elif '-' in item|string %}
            <td style="color: red">{{ item }}</td>
            {% else %}
            <td style="color: black">{{ item }}</td>
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

templates/tournament_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Турніри</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='tables.css') }}"/>
</head>
<body>
<div class="header">
    <a href="{{ url_for('index.index') }}" class="logo">База турнірів по го</a>
    <a href="{{ url_for('tournaments.add_tournament') }}">Завантажити</a>
    <div class="header-right">
        <a href="{{ url_for('players.players') }}">Гравці</a>
        <a href="{{ url_for('tournaments.tournaments') }}" class="active">Турніри</a>
    </div>
</div>

<div class="table-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <p class="{{ category }}">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {{ table | safe }}
</div>
</body>
</html>